CREATE TABLE USERS (
    UserID BIGINT AUTO_INCREMENT PRIMARY KEY,
    Email VARCHAR(255) NOT NULL UNIQUE,
    Name VARCHAR(255) NOT NULL,
    Password VARCHAR(255) NOT NULL,
    PhoneNo VARCHAR(20),
    Role VARCHAR(50) NOT NULL,
    IsVerified BOOLEAN NOT NULL DEFAULT FALSE,
    IsEnabled BOOLEAN NOT NULL DEFAULT FALSE,
    Active BOOLEAN NOT NULL DEFAULT TRUE,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    ModifiedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE VENDORS (
    VendorID BIGINT AUTO_INCREMENT PRIMARY KEY,
    UserID BIGINT NOT NULL,
    GSTNumber VARCHAR(255),
    CompanyName VARCHAR(255),
    Category VARCHAR(255),
    Address VARCHAR(255),
    Active BOOLEAN NOT NULL DEFAULT TRUE,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    ModifiedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_VENDORS_USER FOREIGN KEY (UserID) REFERENCES USERS(UserID)
);

CREATE TABLE RFQS (
    RFQID BIGINT AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(255),
    Description VARCHAR(255),
    Category VARCHAR(255),
    Deadline DATETIME,
    Status VARCHAR(50),
    Active BOOLEAN NOT NULL DEFAULT TRUE,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    ModifiedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE RFQITEMMAPPING (
    RFQItemMappingID BIGINT AUTO_INCREMENT PRIMARY KEY,
    RFQID BIGINT NOT NULL,
    ItemName VARCHAR(255),
    Unit VARCHAR(255),
    Quantity INT,
    Active BOOLEAN NOT NULL DEFAULT TRUE,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    ModifiedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_RFQITEMMAPPING_RFQ FOREIGN KEY (RFQID) REFERENCES RFQS(RFQID)
);

CREATE TABLE RFQVENDORMAPPING (
    RFQVendorMappingID BIGINT AUTO_INCREMENT PRIMARY KEY,
    RFQID BIGINT NOT NULL,
    VendorID BIGINT NOT NULL,
    Active BOOLEAN NOT NULL DEFAULT TRUE,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    ModifiedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_RFQVENDORMAPPING_RFQ FOREIGN KEY (RFQID) REFERENCES RFQS(RFQID),
    CONSTRAINT FK_RFQVENDORMAPPING_VENDOR FOREIGN KEY (VendorID) REFERENCES VENDORS(VendorID)
);

CREATE TABLE QUOTATIONS (
    QuotationID BIGINT AUTO_INCREMENT PRIMARY KEY,
    RFQID BIGINT NOT NULL,
    VendorID BIGINT NOT NULL,
    Status VARCHAR(50),
    Active BOOLEAN NOT NULL DEFAULT TRUE,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    ModifiedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_QUOTATIONS_RFQ FOREIGN KEY (RFQID) REFERENCES RFQS(RFQID),
    CONSTRAINT FK_QUOTATIONS_VENDOR FOREIGN KEY (VendorID) REFERENCES VENDORS(VendorID),
    CONSTRAINT UQ_QUOTATIONS_RFQ_VENDOR UNIQUE (RFQID, VendorID)
);

CREATE TABLE QUOTATIONITEMS (
    QuotationItemID BIGINT AUTO_INCREMENT PRIMARY KEY,
    QuotationID BIGINT NOT NULL,
    RFQItemMappingID BIGINT NOT NULL,
    Price DECIMAL(18, 2),
    DeliveryTime VARCHAR(255),
    Active BOOLEAN NOT NULL DEFAULT TRUE,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    ModifiedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_QUOTATIONITEMS_QUOTATION FOREIGN KEY (QuotationID) REFERENCES QUOTATIONS(QuotationID),
    CONSTRAINT FK_QUOTATIONITEMS_RFQ_ITEM FOREIGN KEY (RFQItemMappingID) REFERENCES RFQITEMMAPPING(RFQItemMappingID),
    CONSTRAINT UQ_QUOTATIONITEMS_QUOTATION_ITEM UNIQUE (QuotationID, RFQItemMappingID)
);
