CREATE TABLE USERS (
    UserID BIGINT AUTO_INCREMENT PRIMARY KEY,

    Email VARCHAR(255) NOT NULL UNIQUE,
    Name VARCHAR(255) NOT NULL,
    Password VARCHAR(255) NOT NULL,

    PhoneNo VARCHAR(20),

    Role VARCHAR(50) NOT NULL,

    CompanyName VARCHAR(255),

    AdditionalInfo TEXT,

    IsVerified BOOLEAN NOT NULL DEFAULT FALSE,

	IsEnabled BOOLEAN NOT NULL DEFAULT FALSE,

    Active BOOLEAN NOT NULL DEFAULT TRUE,

    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    ModifiedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);